name: Typst PDF Generation

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-gnu.tar.gz -o typst.tar.gz
          tar -xzf typst.tar.gz
          sudo mv typst /usr/local/bin/
          typst --version

      - name: Copy JSON data file
        run: cp data.json input_data.json


      - name: Generate PDF from Typst template
        run: |
          mkdir -p output
          typst compile main.typ output/resume.pdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Generated Resume PDF
          path: output/resume.pdf
